name: integration_tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install asn1crypto uvicorn starlette httpx
      - name: Install system packages
        run: |
          sudo apt-get install apache2 apache2-dev nginx haproxy make
      - name: Generate certifcates
        run: |
          make -C tests certs
      - name: Start uvicorn
        run: |
          uvicorn tests:app &
      - name: Start apache2
        run: |
          make -C tests httpd &
      - name: Start nginx
        run:
          make -C tests nginx &
      - name: Start haproxy
        run:
          make -C tests haproxy &
      - name: Run tests
        run: |
          sleep 5
          python tests/client.py
